server:
  port: 2020
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/photo_app
    username: pratik
    password: pratik 
  
  jpa:    hibernate:      ddl-auto: create-drop
    show-sql: true
    properties:      hibernate:
        "[format_sql]": true

tokenSecret: ash3jdasljfasdjasdji12kdf